In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
print(arr+1)

[2 3 4 5 6 7]


In [6]:
print(arr+1)

[2 3 4 5 6 7]


In [ ]:
print(arr-1)

In [8]:
print(arr*2)

[ 2  4  6  8 10 12]


In [7]:
print(arr % 3)

[1 2 0 1 2 0]


In [9]:
print(arr/2)

[0.5 1.  1.5 2.  2.5 3. ]


In [10]:
print(arr**2)

[ 1  4  9 16 25 36]


In [11]:
arr.min()

1

In [12]:
arr.max()

6

In [ ]:
arr=np.array([



               ])