In [1]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5,6,7,8])


In [4]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [10]:
arr[3]

4

In [12]:
arr[3:]

array([4, 5, 6, 7, 8])

In [14]:
arr[ : -3]

array([1, 2, 3, 4, 5])

In [15]:
arr[3:-3]

array([4, 5])

In [17]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [18]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [19]:
arr[3,1]

3

In [21]:
arr[ 1 :, 1 :]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [22]:
arr[2,3]

5

In [23]:
arr[3,3]

1

In [24]:
arr[3,1]

3