In [2]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[8,7,6,5],[4,3,2,1]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [6]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [7]:
np.vstack((arr2,arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [9]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [17]:
np.concatenate((arr2,arr1),axis=1)

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [16]:
arr=np.concatenate((arr2,arr1),axis=0)

In [18]:
arr

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.split(arr,2)

[array([[8, 7, 6, 5],
        [4, 3, 2, 1]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [20]:
np.hsplit(arr,2)

[array([[8, 7],
        [4, 3],
        [1, 2],
        [5, 6]]),
 array([[6, 5],
        [2, 1],
        [3, 4],
        [7, 8]])]

In [21]:
np.vsplit(arr,2)

[array([[8, 7, 6, 5],
        [4, 3, 2, 1]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]