In [1]:
!pip install numpy

In [2]:
import numpy as np

In [15]:
 lst = [[1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]]

In [5]:
type(lst)

list

In [16]:
arr=np.array(lst)

In [17]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
type(arr)

numpy.ndarray

In [18]:
arr.ndim

2

In [19]:
arr.shape


(3, 5)

In [20]:
arr.size

15

In [21]:
arr.dtype

dtype('int64')

In [22]:
zeros=np.zeros((5,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
ones=np.ones((3,5))

In [25]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])