In [1]:
import numpy as np

In [13]:
arr =np.random.random((3,4))

In [6]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
arr

array([[0.38398857, 0.76765732, 0.8543376 , 0.86877689],
       [0.12525579, 0.68613568, 0.06532077, 0.38813846],
       [0.22276279, 0.35826881, 0.59035254, 0.44756579]])

In [17]:
arr=np.reshape(arr,(4,3))

In [18]:
arr

array([[0.38398857, 0.76765732, 0.8543376 ],
       [0.86877689, 0.12525579, 0.68613568],
       [0.06532077, 0.38813846, 0.22276279],
       [0.35826881, 0.59035254, 0.44756579]])

In [19]:
arr.flatten()

array([0.38398857, 0.76765732, 0.8543376 , 0.86877689, 0.12525579,
       0.68613568, 0.06532077, 0.38813846, 0.22276279, 0.35826881,
       0.59035254, 0.44756579])